name: Code Check

on:
  pull_request:
    branches:
      - main
		paths-ignore:
		- "*.md"
		- "LICENSE"
		- ".vscode"
		- ".husky"
		- "assets"

jobs:
  check-code:
    runs-on: macos-10.15

    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install changed package dependencies and build packages
        run: |-
          # failure automatically retries 3 times
          pnpm i || pnpm i || pnpm i

      - name: Build back-end
        run: pnpm -F chatgpt-app-service build

      - name: Build front-end
        run: pnpm build
